### ISSUE TITLE
type tooltip popup is not working correctly

### ISSUE THREAD

**Issue by rvion** [haskelly-dev/Haskelly#28]
type tooltips are __really__ broken in many ways 😄 
  

🔶 
![image](https://cloud.githubusercontent.com/assets/2150990/22971203/417bf678-f375-11e6-93b5-050adb1d25ea.png)

🔴 
![image](https://cloud.githubusercontent.com/assets/2150990/22971770/219f9ec0-f377-11e6-93f1-6aff0f536fd4.png)

etc.

__intero has a great support for type query of a given selection:__

```
:type-at 
    "<module-name/filepath>"
    <start line> <start column>
    <end line>
    <end column>
    "<sample string>"

:all-types
```
( see https://github.com/commercialhaskell/intero/issues/29, or https://github.com/commercialhaskell/intero/pull/30)

__without the ability to display the type of the smallest expression enclosing the selection, type tooltips are really not usefull.__

example from sublime text:
   
here, you can see in cyan the smallest enclosing expression, along its type

   <img width="256" alt="capture d ecran 2015-07-28 a 13 39 40" src="https://cloud.githubusercontent.com/assets/2150990/8956232/ed2b2bec-35f3-11e5-920e-1dea3c369093.png">
   <img width="260" alt="capture d ecran 2015-07-28 a 13 39 32" src="https://cloud.githubusercontent.com/assets/2150990/8956231/ed2aee2a-35f3-11e5-94c5-927a0f24ee6c.png">

example from atom :

![image](https://cloud.githubusercontent.com/assets/2150990/15269839/0efffc1e-1a0c-11e6-810b-133e56baf617.png)
here, I select `" "`, and ghc-mod detect that the smallest enclosing expression is `concat3 "aa" "bb"`that have type `String -> String`

**Comment by martrik** [comment]
I guess this might be related to #22 in scenarios related to strings, and it should be straight forward to fix. 

Regarding the second scenario, VS Code doesn't seem to have a way of easily get and highlight the minimal meaningful expression. And I'm not entirely sure how we could get that information ourselves or through Intero. Do you have any idea @rvion ? 

NB: From what I've seen VS Code doesn't seem to care about the selection when it comes to providing type tooltips. It just uses the word which is being hovered.

**Comment by rvion** [comment]
@martrik 

I think it is indeed related to #22, but I don't think that

> we'll try [...] to better parse the word that's being hovered by taking into account quotation marks

is a good idea.

> I'm not entirely sure how we could get that information ourselves or through Intero. 

If you call 
```
:type-at 
    "<module-name/filepath>"
    <start line> <start column>
    <end line>
    <end column>
    "<sample string>"
``
in intero, with the highlighted word, intero will automatically return the type of the smallest enclosing expression so `String`.

Internally, intero have access to all expressions enclosing your selection along their types. it just takes the smallest one and return it's type. It would be a "simple" PR to enable intero to return the span along the type (and please, if you have some time to dedicate to Haskelly, I really think it would be great to do it. I can provide a few pointers if you want)

even without the span, intero will gives you the correct information

**Comment by martrik** [comment]
Currently, Haskelly gets the wrapping word from the hover position that we get from VS Code and send that to Intero with the `type-at` command. What do you think that we should do differently so Intero provides us with the correct type?

**Comment by rvion** [comment]
let me check right now manually, I have an idea about what's going on

**Comment by rvion** [comment]
if I have this file (screenshot given to see line numbers): 

![image](https://cloud.githubusercontent.com/assets/2150990/22980562/3088b552-f39a-11e6-8b5c-a77ffaf9fd3c.png)

```haskell 
module Lib
  ( someFunc
  ) where

someFunc :: IO ()
someFunc =do -- 22 ->  <- 24
  putStrLn "someFunc ok ok"
  print 3
```

when I start intero manually:

```
stack exec intero
Intero 0.1.20 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.
Prelude> :l src/Lib.hs
[1 of 1] Compiling Lib              ( src/Lib.hs, interpreted )
Ok, modules loaded: Lib.
Collecting type info for 1 module(s) ...
```

and ask for the type of the middle "ok" word

```
*Lib> :type-at "Lib" 7 22 7 24 ""
 :: [Char]
```

I have the correct solution.

so I conclude that Haskelly doesn't call intero correctly.

### why did I omit the last param and gave an empty string ("") instead  of "ok" ?

Because I recall that if intero can't find the type of the given span, it used to fallback to checking the type of the given string in its global context.

here is an exemple where I give a wrong span
```
*Lib> :type-at "Lib" 12 223 14 243 "print"
print :: forall a. Show a => a -> IO ()
```

and you can see it returns the type of print. (as if I typed `:t print`)
For this reason, I prefer to give an empty string to know if my request failed.
I don't think this is a great behavior, and I think it would be better if that changed.
there is several possible ways to change that, though.

/cc @chrisdone

### what happens if the module is properly loaded, when I give a random string as the last param ?

```
*Lib> :type-at "Lib" 7 22 7 24 "ok"
ok :: [Char]

*Lib> :type-at "Lib" 7 22 7 24 "print"
print :: [Char]

:type-at "Lib" 7 22 7 24 "omelette du fromage"
omelette du fromage :: [Char]
```

I said in my previous post:

> Internally, intero have access to all expressions enclosing your selection along their types. it just takes the smallest one and return it's type. It would be a "simple" PR to enable intero to return the span along the type (and please, if you have some time to dedicate to Haskelly, I really think it would be great to do it. I can provide a few pointers if you want)

I think having access to the span of the smallest enclosing exception would improve the quality of all intero plugins when users ask the type of a non-complete expression

### what goes wrong in Haskelly ?

I don't really know, but:

- Maybe you don't call intero correctly ?
- Maybe you send span with line numbers off by one  ?
- maybe you include the selected string and intero tries to find its type discarding the span ?

**Comment by rvion** [comment]
Oh, I also forgot:

> VS Code doesn't seem to have a way of easily get and highlight the minimal meaningful expression.

I don't know how hard it is, but the [vscode-todo-highlight extension](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) seems to do it

![image](https://github.com/wayou/vscode-todo-highlight/raw/master/assets/toggle-highlight.gif)

and the code doesn't look too scary at first sight

https://github.com/wayou/vscode-todo-highlight/blob/master/src/extension.js#L61
https://github.com/wayou/vscode-todo-highlight/blob/master/src/extension.js#L95

that's a bit orthogonal to the original issue, but anyway :)

**Comment by martrik** [comment]
We've released a new version (0.4.17) that should fix the issues described above. Can you confirm it? :)

**Comment by martrik** [comment]
Regarding the highlight, it is certainly possible through the styling functionalities. One issue that I can think of though is that we don't get any callback when the hover has finished. Therefore I'm not sure when we should get rid of the highlight.

**Comment by rvion** [comment]
@martrik can't try right now, but I think it is not fixed. 

I just reviewed your commit https://github.com/haskelly-dev/Haskelly/commit/5c25433cd8fda92b06b2863d8b34014d88152e62#commitcomment-20922593

---------

I don't want to sound annoying, but here are two tips

1. don't hesitate to reference issues in your commits:
you can paste the url of this page, or just write #(issue-number) either in the commit name or the commit comment. This way, you'll have a notification like just above. 

2. I would advice you to take the habit of solve issues by 
  1. creating a ne branches
  2. pushing your commit
  3 opening a PR
  4 referencing the issue the PR is trying to fix
  5 keep the original issue discussion to try to understand the issue, and the PR discussion to discuss the fix

**Comment by rvion** [comment]
also, to explore type efficiently, could you add an option to trigger the type hover on selection update ?

**Comment by rvion** [comment]
🔶  also, you still call `:type-at` with the last position filled with "${word}" (which is IMO not really good.)

especially with code like 

```
+    if (first === '\'' || last === '\'') {
+        cleanWord = cleanWord.slice(0, cleanWord.length - 1);
+        cleanWord = cleanWord.substring(1);
+    }
```

around. If I read that correctly, I think it's buggy for names like `foldl'` (notice the `'`) at the end.

I would also really advice you to write a small test suite for this kind of functions. those are sneaky to get right :)

**Comment by martrik** [comment]
Thanks for all your advices. After some research we've realised that VS Code's type hovering is not designed to take into account text selection. In particular three two points make us believe this: 

1. VS Code type hover for JS and TypeScript doesn't involve selection. It just uses the closest
2. VS Code provides the extension with a position in the line, which might not be the start of a word

Therefore we have decided to not adjust the type hover depending on the selection. After doing some tests we've seen that type hover seems to work correctly (version 0.4.19) so I'll now close this issue. If anyone finds any counter example, please reopen the issue and let us know what word is causing an issue. Thanks!

PS: @rvion There's no way of triggering type hover without a previous request coming from the IDE. Because of that we can't implement your suggestion of updating the type hover on selection change.
